/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidad.vistas;

import AccesoADatos.Conexion;
import AccesoADatos.MateriaData;
import Entidades.Materia;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;

/**
 *
 * @author 4K
 */
public class FormularioMateriaView extends javax.swing.JInternalFrame {
private MateriaData  materiaData = new MateriaData();
    private Materia materiaActual = null;
    
    /**
     * Creates new form FormularioMateriaView
     */
    public FormularioMateriaView() {
        initComponents();
        Conexion.getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1Materia = new javax.swing.JLabel();
        jLabel2Codigo = new javax.swing.JLabel();
        jLabel3Nombre = new javax.swing.JLabel();
        jLabel4Anio = new javax.swing.JLabel();
        jLabel5Estado = new javax.swing.JLabel();
        jTextField1Codigo = new javax.swing.JTextField();
        jTextField2Nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3Anio = new javax.swing.JTextField();
        jRadioButton1Estado = new javax.swing.JRadioButton();
        jButton1Buscar = new javax.swing.JButton();
        jButton2Nuevo = new javax.swing.JButton();
        jButton3Eliminar = new javax.swing.JButton();
        jButton4GuardarGuardar = new javax.swing.JButton();
        jButton5Salir = new javax.swing.JButton();

        jTextField4.setText("jTextField4");

        jLabel1Materia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1Materia.setText("Materia");

        jLabel2Codigo.setText("Codigo");

        jLabel3Nombre.setText("Nombre");

        jLabel4Anio.setText("Año");

        jLabel5Estado.setText("Estado");

        jTextField1Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1CodigoActionPerformed(evt);
            }
        });

        jButton1Buscar.setText("Buscar");
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });

        jButton2Nuevo.setText("Nuevo");
        jButton2Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2NuevoActionPerformed(evt);
            }
        });

        jButton3Eliminar.setText("Eliminar");
        jButton3Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EliminarActionPerformed(evt);
            }
        });

        jButton4GuardarGuardar.setText("Guardar");
        jButton4GuardarGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4GuardarGuardarActionPerformed(evt);
            }
        });

        jButton5Salir.setText("Salir");
        jButton5Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1Materia))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2Codigo)
                                .addGap(27, 27, 27)
                                .addComponent(jTextField1Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1Buscar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3Nombre)
                                    .addComponent(jLabel4Anio)
                                    .addComponent(jLabel5Estado))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1Estado)
                                    .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton2Nuevo)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3Eliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4GuardarGuardar)))
                        .addGap(18, 18, 18)
                        .addComponent(jButton5Salir)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1Materia)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2Codigo)
                    .addComponent(jTextField1Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1Buscar))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Nombre)
                    .addComponent(jTextField2Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Anio)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3Anio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5Estado)
                    .addComponent(jRadioButton1Estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2Nuevo)
                    .addComponent(jButton3Eliminar)
                    .addComponent(jButton4GuardarGuardar)
                    .addComponent(jButton5Salir))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1CodigoActionPerformed

    private void jButton2NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2NuevoActionPerformed

limpiarCampos();
    materiaActual= null;







        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2NuevoActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed
try {
            Integer id = Integer.parseInt(jTextField1Codigo.getText()); 
                         //Integer.parseInt(jTextField3Anio.getText()); 
                    
            materiaActual= materiaData.buscarMateria(id);
            
            if (materiaActual!=null) {
        jTextField2Nombre.setText(materiaActual.getNombre());
        
          jTextField3Anio.setText(Integer.toString(materiaActual.getAnioMateria()));
       // jTextField3Anio.setText(materiaActual.getAnioMateria());
        
        jRadioButton1Estado.setSelected(materiaActual.isActivo());
              
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showConfirmDialog(null, "Debe ingresar un numero valido");
        }





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jButton3EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3EliminarActionPerformed
if(materiaActual!=null){

materiaData.eliminarMateria(materiaActual.getIdMateria());
materiaActual=null;
limpiarCampos();
}else{
JOptionPane.showMessageDialog(this,"no hay alumno seleccionado");
}




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3EliminarActionPerformed

    private void jButton4GuardarGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4GuardarGuardarActionPerformed


        try{
    Integer idMateria = Integer.parseInt(jTextField1Codigo.getText());
    String nombre= jTextField2Nombre.getText();
    Integer anioMateria=Integer.parseInt(jTextField3Anio.getText());

    if(nombre.isEmpty()|| anioMateria==null){
      
        JOptionPane.showMessageDialog(this, "no puede haber campos vacios");
        return;
}

Boolean estado=jRadioButton1Estado.isSelected();

if(materiaActual==null){
   
    materiaActual=new Materia(idMateria, nombre,anioMateria, estado);
    materiaData.guardarMateria(materiaActual);

}else{

materiaActual.setIdMateria(idMateria);

materiaActual.setNombre(nombre);

materiaData.modificarMateria(materiaActual);

}


}catch(NumberFormatException nfe){

   JOptionPane.showMessageDialog(this, "Debe ingresar un Dni valido");

}






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4GuardarGuardarActionPerformed

    private void jButton5SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5SalirActionPerformed

dispose();





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5SalirActionPerformed
 private void limpiarCampos(){
      
        
       jTextField1Codigo.setText("");
       jTextField2Nombre.setText("");
       jTextField3Anio.setText("");
       jRadioButton1Estado.setSelected(true);
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton2Nuevo;
    private javax.swing.JButton jButton3Eliminar;
    private javax.swing.JButton jButton4GuardarGuardar;
    private javax.swing.JButton jButton5Salir;
    private javax.swing.JLabel jLabel1Materia;
    private javax.swing.JLabel jLabel2Codigo;
    private javax.swing.JLabel jLabel3Nombre;
    private javax.swing.JLabel jLabel4Anio;
    private javax.swing.JLabel jLabel5Estado;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1Estado;
    private javax.swing.JTextField jTextField1Codigo;
    private javax.swing.JTextField jTextField2Nombre;
    private javax.swing.JTextField jTextField3Anio;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
