/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.vistas;

import AccesoADatos.AlumnoData;
import AccesoADatos.Conexion;
import Entidades.Alumno;


import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class FormularioAlumnoView extends javax.swing.JFrame {
private AlumnoData  alumnoData = new AlumnoData();
    private Alumno alumnoActual = null;
    
   
    
    /**
     * Creates new form FormularioAlumnoView
     */
    public FormularioAlumnoView() {
        initComponents();
        Conexion.getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Alumno = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3Apellido = new javax.swing.JLabel();
        jLabel4Nombre = new javax.swing.JLabel();
        jLabel5Estado = new javax.swing.JLabel();
        jLabel6FechaDeNacimiento = new javax.swing.JLabel();
        jTextField1Dni = new javax.swing.JTextField();
        jTextField2Apellido = new javax.swing.JTextField();
        jTextField3Nombre = new javax.swing.JTextField();
        jRadioButton1Estado = new javax.swing.JRadioButton();
        jButton1Buscar = new javax.swing.JButton();
        jButton2Nuevo = new javax.swing.JButton();
        jButton3Eliminar = new javax.swing.JButton();
        jButton4Guardar = new javax.swing.JButton();
        jButton5Salir = new javax.swing.JButton();
        jDateChooser1Fecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1Alumno.setText("Alumno");

        jLabel2.setText("Documento:");

        jLabel3Apellido.setText("Apellido");

        jLabel4Nombre.setText("Nombre");

        jLabel5Estado.setText("Estado:");

        jLabel6FechaDeNacimiento.setText("Fecha de nacimiento");

        jTextField3Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3NombreActionPerformed(evt);
            }
        });

        jButton1Buscar.setText("Buscar");
        jButton1Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarActionPerformed(evt);
            }
        });

        jButton2Nuevo.setText("Nuevo");
        jButton2Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2NuevoActionPerformed(evt);
            }
        });

        jButton3Eliminar.setText("Eliminar");
        jButton3Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3EliminarActionPerformed(evt);
            }
        });

        jButton4Guardar.setText("Guardar");
        jButton4Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4GuardarActionPerformed(evt);
            }
        });

        jButton5Salir.setText("Salir");
        jButton5Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1Alumno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3Apellido)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4Nombre)
                            .addComponent(jLabel5Estado)
                            .addComponent(jLabel6FechaDeNacimiento))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jButton1Buscar))
                            .addComponent(jTextField2Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField3Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1Estado)
                            .addComponent(jDateChooser1Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2Nuevo)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3Eliminar)
                        .addGap(27, 27, 27)
                        .addComponent(jButton4Guardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5Salir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1Alumno)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Apellido)
                    .addComponent(jTextField2Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4Nombre)
                    .addComponent(jTextField3Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5Estado)
                    .addComponent(jRadioButton1Estado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6FechaDeNacimiento)
                    .addComponent(jDateChooser1Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2Nuevo)
                    .addComponent(jButton3Eliminar)
                    .addComponent(jButton4Guardar)
                    .addComponent(jButton5Salir))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3NombreActionPerformed

    private void jButton1BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarActionPerformed

try {
            Integer dni = Integer.parseInt(jTextField1Dni.getText());
            alumnoActual= alumnoData.buscarAlumnoPorDni(dni);
            
            if (alumnoActual!=null) {
        jTextField3Nombre.setText(alumnoActual.getNombre());
        jTextField2Apellido.setText(alumnoActual.getApellido());
        jRadioButton1Estado.setSelected(alumnoActual.isActivo());
        LocalDate lc= alumnoActual.getFechanacimiento();
        java.util.Date date= java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
        jDateChooser1Fecha.setDate(date);
      
                
                
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showConfirmDialog(null, "Debe ingresar un numero valido");
        }







        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1BuscarActionPerformed

    private void jButton2NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2NuevoActionPerformed
    limpiarCampos();
    alumnoActual= null;




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2NuevoActionPerformed

    private void jButton4GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4GuardarActionPerformed


        try{
    Integer dni = Integer.parseInt(jTextField1Dni.getText());
    String nombre=jTextField3Nombre.getText();
    String apellido=jTextField2Apellido.getText();

    if(nombre.isEmpty()|| apellido.isEmpty()){
      
        JOptionPane.showMessageDialog(this, "no puede haber campos vacios");
        return;
}
java.util.Date sfecha=jDateChooser1Fecha.getDate();
LocalDate fechanacimiento=sfecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
Boolean estado=jRadioButton1Estado.isSelected();

if(alumnoActual==null){
   
    alumnoActual=new Alumno(dni, apellido, nombre,fechanacimiento, estado);
    alumnoData.guardarAlumno(alumnoActual);

}else{

  alumnoActual.setDni(dni);
alumnoActual.setApellido(apellido);
alumnoActual.setNombre(nombre);
alumnoActual.setFechanacimiento(fechanacimiento);

alumnoData.modificarAlumno(alumnoActual);

}


}catch(NumberFormatException nfe){

   JOptionPane.showMessageDialog(this, "Debe ingresar un Dni valido");

}






        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4GuardarActionPerformed

    private void jButton5SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5SalirActionPerformed

dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5SalirActionPerformed

    private void jButton3EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3EliminarActionPerformed

if(alumnoActual!=null){

alumnoData.eliminarAlumno(alumnoActual.getIdAlumno());
alumnoActual=null;
limpiarCampos();
}else{
JOptionPane.showMessageDialog(this,"no hay alumno seleccionado");
}



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3EliminarActionPerformed

    private void limpiarCampos(){
      
        
       jTextField1Dni.setText("");
       jTextField2Apellido.setText("");
       jTextField3Nombre.setText("");
       jRadioButton1Estado.setSelected(true);
       //jDateChooser1Fecha.setDate(new Date);
      
 
     
      
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioAlumnoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioAlumnoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioAlumnoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioAlumnoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioAlumnoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Buscar;
    private javax.swing.JButton jButton2Nuevo;
    private javax.swing.JButton jButton3Eliminar;
    private javax.swing.JButton jButton4Guardar;
    private javax.swing.JButton jButton5Salir;
    private com.toedter.calendar.JDateChooser jDateChooser1Fecha;
    private javax.swing.JLabel jLabel1Alumno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3Apellido;
    private javax.swing.JLabel jLabel4Nombre;
    private javax.swing.JLabel jLabel5Estado;
    private javax.swing.JLabel jLabel6FechaDeNacimiento;
    private javax.swing.JRadioButton jRadioButton1Estado;
    private javax.swing.JTextField jTextField1Dni;
    private javax.swing.JTextField jTextField2Apellido;
    private javax.swing.JTextField jTextField3Nombre;
    // End of variables declaration//GEN-END:variables
}
